(function(y,Z,qa,n){function L(a,b,c){return setTimeout(M(a,c),b)}function u(a,b,c){return Array.isArray(a)?(p(a,c[b],c),!0):!1}function p(a,b,c){var d;if(a)if(a.forEach)a.forEach(b,c);else if(a.length!==n)for(d=0;d<a.length;)b.call(c,a[d],d,a),d++;else for(d in a)a.hasOwnProperty(d)&&b.call(c,a[d],d,a)}function r(a,b,c){for(var d=Object.keys(b),e=0;e<d.length;){if(!c||c&&a[d[e]]===n)a[d[e]]=b[d[e]];e++}return a}function N(a,b){return r(a,b,!0)}function h(a,b,c){b=b.prototype;var d;d=a.prototype=
Object.create(b);d.constructor=a;d._super=b;c&&r(d,c)}function M(a,b){return function(){return a.apply(b,arguments)}}function O(a,b){return"function"==typeof a?a.apply(b?b[0]||n:n,b):a}function z(a,b,c){p(A(b),function(b){a.addEventListener(b,c,!1)})}function B(a,b,c){p(A(b),function(b){a.removeEventListener(b,c,!1)})}function aa(a,b){for(;a;){if(a==b)return!0;a=a.parentNode}return!1}function A(a){return a.trim().split(/\s+/g)}function v(a,b,c){if(a.indexOf&&!c)return a.indexOf(b);for(var d=0;d<a.length;){if(c&&
a[d][c]==b||!c&&a[d]===b)return d;d++}return-1}function C(a){return Array.prototype.slice.call(a,0)}function ba(a,b,c){for(var d=[],e=[],f=0;f<a.length;){var g=b?a[f][b]:a[f];0>v(e,g)&&d.push(a[f]);e[f]=g;f++}c&&(d=b?d.sort(function(a,c){return a[b]>c[b]}):d.sort());return d}function D(a,b){for(var c,d=b[0].toUpperCase()+b.slice(1),e=0;e<ca.length;){c=(c=ca[e])?c+d:b;if(c in a)return c;e++}return n}function da(a){a=a.ownerDocument;return a.defaultView||a.parentWindow}function l(a,b){var c=this;this.manager=
a;this.callback=b;this.element=a.element;this.target=a.options.inputTarget;this.domHandler=function(b){O(a.options.enable,[a])&&c.handler(b)};this.init()}function ra(a){var b=a.options.inputClass;return new (b?b:sa?P:ta?E:ea?Q:F)(a,ua)}function ua(a,b,c){var d=c.pointers.length,e=c.changedPointers.length,f=b&1&&0===d-e;c.isFirst=!!f;c.isFinal=!!(b&12&&0===d-e);f&&(a.session={});c.eventType=b;b=a.session;d=c.pointers;e=d.length;b.firstInput||(b.firstInput=fa(c));1<e&&!b.firstMultiple?b.firstMultiple=
fa(c):1===e&&(b.firstMultiple=!1);var f=b.firstInput,g=(e=b.firstMultiple)?e.center:f.center,k=c.center=ga(d);c.timeStamp=R();c.deltaTime=c.timeStamp-f.timeStamp;c.angle=S(g,k);c.distance=G(g,k);var f=c.center,g=b.offsetDelta||{},k=b.prevDelta||{},h=b.prevInput||{};if(1===c.eventType||4===h.eventType)k=b.prevDelta={x:h.deltaX||0,y:h.deltaY||0},g=b.offsetDelta={x:f.x,y:f.y};c.deltaX=k.x+(f.x-g.x);c.deltaY=k.y+(f.y-g.y);c.offsetDirection=ha(c.deltaX,c.deltaY);e?(f=e.pointers,f=G(d[0],d[1],H)/G(f[0],
f[1],H)):f=1;c.scale=f;e?(e=e.pointers,d=S(d[1],d[0],H)-S(e[1],e[0],H)):d=0;c.rotation=d;g=b.lastInterval||c;d=c.timeStamp-g.timeStamp;8!=c.eventType&&(25<d||g.velocity===n)?(f=g.deltaX-c.deltaX,g=g.deltaY-c.deltaY,k=f/d||0,h=g/d||0,d=k,e=h,k=x(k)>x(h)?k:h,f=ha(f,g),b.lastInterval=c):(k=g.velocity,d=g.velocityX,e=g.velocityY,f=g.direction);c.velocity=k;c.velocityX=d;c.velocityY=e;c.direction=f;b=a.element;aa(c.srcEvent.target,b)&&(b=c.srcEvent.target);c.target=b;a.emit("hammer.input",c);a.recognize(c);
a.session.prevInput=c}function fa(a){for(var b=[],c=0;c<a.pointers.length;)b[c]={clientX:w(a.pointers[c].clientX),clientY:w(a.pointers[c].clientY)},c++;return{timeStamp:R(),pointers:b,center:ga(b),deltaX:a.deltaX,deltaY:a.deltaY}}function ga(a){var b=a.length;if(1===b)return{x:w(a[0].clientX),y:w(a[0].clientY)};for(var c=0,d=0,e=0;e<b;)c+=a[e].clientX,d+=a[e].clientY,e++;return{x:w(c/b),y:w(d/b)}}function ha(a,b){return a===b?1:x(a)>=x(b)?0<a?2:4:0<b?8:16}function G(a,b,c){c||(c=ia);var d=b[c[0]]-
a[c[0]];a=b[c[1]]-a[c[1]];return Math.sqrt(d*d+a*a)}function S(a,b,c){c||(c=ia);return 180*Math.atan2(b[c[1]]-a[c[1]],b[c[0]]-a[c[0]])/Math.PI}function F(){this.evEl=va;this.evWin=wa;this.allow=!0;this.pressed=!1;l.apply(this,arguments)}function P(){this.evEl=ja;this.evWin=ka;l.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function la(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";this.started=!1;l.apply(this,arguments)}function E(){this.evTarget=
xa;this.targetIds={};l.apply(this,arguments)}function ya(a,b){var c=C(a.touches),d=this.targetIds;if(b&3&&1===c.length)return d[c[0].identifier]=!0,[c,c];var e,f=C(a.changedTouches),g=[],h=this.target;e=c.filter(function(a){return aa(a.target,h)});if(1===b)for(c=0;c<e.length;)d[e[c].identifier]=!0,c++;for(c=0;c<f.length;)d[f[c].identifier]&&g.push(f[c]),b&12&&delete d[f[c].identifier],c++;if(g.length)return[ba(e.concat(g),"identifier",!0),g]}function Q(){l.apply(this,arguments);var a=M(this.handler,
this);this.touch=new E(this.manager,a);this.mouse=new F(this.manager,a)}function T(a,b){this.manager=a;this.set(b)}function za(a){if(-1<a.indexOf("none"))return"none";var b=-1<a.indexOf("pan-x"),c=-1<a.indexOf("pan-y");return b&&c?"pan-x pan-y":b||c?b?"pan-x":"pan-y":-1<a.indexOf("manipulation")?"manipulation":"auto"}function q(a){this.id=Aa++;this.manager=null;this.options=N(a||{},this.defaults);a=this.options.enable;this.options.enable=a===n?!0:a;this.state=1;this.simultaneous={};this.requireFail=
[]}function ma(a){return 16==a?"down":8==a?"up":2==a?"left":4==a?"right":""}function I(a,b){var c=b.manager;return c?c.get(a):a}function m(){q.apply(this,arguments)}function J(){m.apply(this,arguments);this.pY=this.pX=null}function U(){m.apply(this,arguments)}function V(){q.apply(this,arguments);this._input=this._timer=null}function W(){m.apply(this,arguments)}function X(){m.apply(this,arguments)}function K(){q.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=
0}function t(a,b){b=b||{};var c=b.recognizers;b.recognizers=c===n?t.defaults.preset:c;return new Y(a,b)}function Y(a,b){b=b||{};this.options=N(b,t.defaults);this.options.inputTarget=this.options.inputTarget||a;this.handlers={};this.session={};this.recognizers=[];this.element=a;this.input=ra(this);this.touchAction=new T(this,this.options.touchAction);na(this,!0);p(b.recognizers,function(a){var b=this.add(new a[0](a[1]));a[2]&&b.recognizeWith(a[2]);a[3]&&b.requireFailure(a[3])},this)}function na(a,
b){var c=a.element;p(a.options.cssProps,function(a,e){c.style[D(c.style,e)]=b?a:""})}function Ba(a,b){var c=Z.createEvent("Event");c.initEvent(a,!0,!0);c.gesture=b;b.target.dispatchEvent(c)}var ca=" webkit moz MS ms o".split(" "),Ca=Z.createElement("div"),w=Math.round,x=Math.abs,R=Date.now,Aa=1,Da=/mobile|tablet|ip(ad|hone|od)|android/i,ea="ontouchstart"in y,sa=D(y,"PointerEvent")!==n,ta=ea&&Da.test(navigator.userAgent),ia=["x","y"],H=["clientX","clientY"];l.prototype={handler:function(){},init:function(){this.evEl&&
z(this.element,this.evEl,this.domHandler);this.evTarget&&z(this.target,this.evTarget,this.domHandler);this.evWin&&z(da(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&B(this.element,this.evEl,this.domHandler);this.evTarget&&B(this.target,this.evTarget,this.domHandler);this.evWin&&B(da(this.element),this.evWin,this.domHandler)}};var Ea={mousedown:1,mousemove:2,mouseup:4},va="mousedown",wa="mousemove mouseup";h(F,l,{handler:function(a){var b=Ea[a.type];b&1&&0===a.button&&(this.pressed=
!0);b&2&&1!==a.which&&(b=4);this.pressed&&this.allow&&(b&4&&(this.pressed=!1),this.callback(this.manager,b,{pointers:[a],changedPointers:[a],pointerType:"mouse",srcEvent:a}))}});var Fa={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ga={2:"touch",3:"pen",4:"mouse",5:"kinect"},ja="pointerdown",ka="pointermove pointerup pointercancel";y.MSPointerEvent&&(ja="MSPointerDown",ka="MSPointerMove MSPointerUp MSPointerCancel");h(P,l,{handler:function(a){var b=this.store,c=!1,d=a.type.toLowerCase().replace("ms",
""),d=Fa[d],e=Ga[a.pointerType]||a.pointerType,f="touch"==e,g=v(b,a.pointerId,"pointerId");d&1&&(0===a.button||f)?0>g&&(b.push(a),g=b.length-1):d&12&&(c=!0);0>g||(b[g]=a,this.callback(this.manager,d,{pointers:b,changedPointers:[a],pointerType:e,srcEvent:a}),c&&b.splice(g,1))}});var Ha={touchstart:1,touchmove:2,touchend:4,touchcancel:8};h(la,l,{handler:function(a){var b=Ha[a.type];1===b&&(this.started=!0);if(this.started){var c;c=C(a.touches);var d=C(a.changedTouches);b&12&&(c=ba(c.concat(d),"identifier",
!0));c=[c,d];b&12&&0===c[0].length-c[1].length&&(this.started=!1);this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:a})}}});var Ia={touchstart:1,touchmove:2,touchend:4,touchcancel:8},xa="touchstart touchmove touchend touchcancel";h(E,l,{handler:function(a){var b=Ia[a.type],c=ya.call(this,a,b);c&&this.callback(this.manager,b,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:a})}});h(Q,l,{handler:function(a,b,c){var d="mouse"==c.pointerType;
if("touch"==c.pointerType)this.mouse.allow=!1;else if(d&&!this.mouse.allow)return;b&12&&(this.mouse.allow=!0);this.callback(a,b,c)},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var oa=D(Ca.style,"touchAction"),pa=oa!==n;T.prototype={set:function(a){"compute"==a&&(a=this.compute());pa&&(this.manager.element.style[oa]=a);this.actions=a.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var a=[];p(this.manager.recognizers,function(b){O(b.options.enable,
[b])&&(a=a.concat(b.getTouchAction()))});return za(a.join(" "))},preventDefaults:function(a){if(!pa){var b=a.srcEvent;a=a.offsetDirection;if(this.manager.session.prevented)b.preventDefault();else{var c=this.actions,d=-1<c.indexOf("none"),e=-1<c.indexOf("pan-y"),c=-1<c.indexOf("pan-x");if(d||e&&a&6||c&&a&24)return this.preventSrc(b)}}},preventSrc:function(a){this.manager.session.prevented=!0;a.preventDefault()}};q.prototype={defaults:{},set:function(a){r(this.options,a);this.manager&&this.manager.touchAction.update();
return this},recognizeWith:function(a){if(u(a,"recognizeWith",this))return this;var b=this.simultaneous;a=I(a,this);b[a.id]||(b[a.id]=a,a.recognizeWith(this));return this},dropRecognizeWith:function(a){if(u(a,"dropRecognizeWith",this))return this;a=I(a,this);delete this.simultaneous[a.id];return this},requireFailure:function(a){if(u(a,"requireFailure",this))return this;var b=this.requireFail;a=I(a,this);-1===v(b,a)&&(b.push(a),a.requireFailure(this));return this},dropRequireFailure:function(a){if(u(a,
"dropRequireFailure",this))return this;a=I(a,this);a=v(this.requireFail,a);-1<a&&this.requireFail.splice(a,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(a){return!!this.simultaneous[a.id]},emit:function(a){function b(b){c.manager.emit(c.options.event+(b?d&16?"cancel":d&8?"end":d&4?"move":d&2?"start":"":""),a)}var c=this,d=this.state;8>d&&b(!0);b();8<=d&&b(!0)},tryEmit:function(a){if(this.canEmit())return this.emit(a);this.state=32},canEmit:function(){for(var a=
0;a<this.requireFail.length;){if(!(this.requireFail[a].state&33))return!1;a++}return!0},recognize:function(a){a=r({},a);O(this.options.enable,[this,a])?(this.state&56&&(this.state=1),this.state=this.process(a),this.state&30&&this.tryEmit(a)):(this.reset(),this.state=32)},process:function(a){},getTouchAction:function(){},reset:function(){}};h(m,q,{defaults:{pointers:1},attrTest:function(a){var b=this.options.pointers;return 0===b||a.pointers.length===b},process:function(a){var b=this.state,c=a.eventType,
d=b&6;a=this.attrTest(a);return d&&(c&8||!a)?b|16:d||a?c&4?b|8:b&2?b|4:2:32}});h(J,m,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var a=this.options.direction,b=[];a&6&&b.push("pan-y");a&24&&b.push("pan-x");return b},directionTest:function(a){var b=this.options,c=!0,d=a.distance,e=a.direction,f=a.deltaX,g=a.deltaY;e&b.direction||(b.direction&6?(e=0===f?1:0>f?2:4,c=f!=this.pX,d=Math.abs(a.deltaX)):(e=0===g?1:0>g?8:16,c=g!=this.pY,d=Math.abs(a.deltaY)));a.direction=
e;return c&&d>b.threshold&&e&b.direction},attrTest:function(a){return m.prototype.attrTest.call(this,a)&&(this.state&2||!(this.state&2)&&this.directionTest(a))},emit:function(a){this.pX=a.deltaX;this.pY=a.deltaY;var b=ma(a.direction);b&&this.manager.emit(this.options.event+b,a);this._super.emit.call(this,a)}});h(U,m,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.scale-1)>this.options.threshold||
this.state&2)},emit:function(a){this._super.emit.call(this,a);1!==a.scale&&this.manager.emit(this.options.event+(1>a.scale?"in":"out"),a)}});h(V,q,{defaults:{event:"press",pointers:1,time:500,threshold:5},getTouchAction:function(){return["auto"]},process:function(a){var b=this.options,c=a.pointers.length===b.pointers,d=a.distance<b.threshold,e=a.deltaTime>b.time;this._input=a;if(!d||!c||a.eventType&12&&!e)this.reset();else if(a.eventType&1)this.reset(),this._timer=L(function(){this.state=8;this.tryEmit()},
b.time,this);else if(a.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},emit:function(a){8===this.state&&(a&&a.eventType&4?this.manager.emit(this.options.event+"up",a):(this._input.timeStamp=R(),this.manager.emit(this.options.event,this._input)))}});h(W,m,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.rotation)>this.options.threshold||this.state&2)}});
h(X,m,{defaults:{event:"swipe",threshold:10,velocity:.65,direction:30,pointers:1},getTouchAction:function(){return J.prototype.getTouchAction.call(this)},attrTest:function(a){var b=this.options.direction,c;b&30?c=a.velocity:b&6?c=a.velocityX:b&24&&(c=a.velocityY);return this._super.attrTest.call(this,a)&&b&a.direction&&a.distance>this.options.threshold&&x(c)>this.options.velocity&&a.eventType&4},emit:function(a){var b=ma(a.direction);b&&this.manager.emit(this.options.event+b,a);this.manager.emit(this.options.event,
a)}});h(K,q,{defaults:{event:"tap",pointers:1,taps:1,interval:300,time:250,threshold:2,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(a){var b=this.options,c=a.pointers.length===b.pointers,d=a.distance<b.threshold,e=a.deltaTime<b.time;this.reset();if(a.eventType&1&&0===this.count)return this.failTimeout();if(d&&e&&c){if(4!=a.eventType)return this.failTimeout();c=this.pTime?a.timeStamp-this.pTime<b.interval:!0;d=!this.pCenter||G(this.pCenter,a.center)<b.posThreshold;
this.pTime=a.timeStamp;this.pCenter=a.center;this.count=d&&c?this.count+1:1;this._input=a;if(0===this.count%b.taps)return this.hasRequireFailures()?(this._timer=L(function(){this.state=8;this.tryEmit()},b.interval,this),2):8}return 32},failTimeout:function(){this._timer=L(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});t.VERSION=
"2.0.4";t.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,preset:[[W,{enable:!1}],[U,{enable:!1},["rotate"]],[X,{direction:6}],[J,{direction:6},["swipe"]],[K],[K,{event:"doubletap",taps:2},["tap"]],[V]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};Y.prototype={set:function(a){r(this.options,a);a.touchAction&&this.touchAction.update();a.inputTarget&&(this.input.destroy(),
this.input.target=a.inputTarget,this.input.init());return this},stop:function(a){this.session.stopped=a?2:1},recognize:function(a){var b=this.session;if(!b.stopped){this.touchAction.preventDefaults(a);var c,d=this.recognizers,e=b.curRecognizer;if(!e||e&&e.state&8)e=b.curRecognizer=null;for(var f=0;f<d.length;)c=d[f],2===b.stopped||e&&c!=e&&!c.canRecognizeWith(e)?c.reset():c.recognize(a),!e&&c.state&14&&(e=b.curRecognizer=c),f++}},get:function(a){if(a instanceof q)return a;for(var b=this.recognizers,
c=0;c<b.length;c++)if(b[c].options.event==a)return b[c];return null},add:function(a){if(u(a,"add",this))return this;var b=this.get(a.options.event);b&&this.remove(b);this.recognizers.push(a);a.manager=this;this.touchAction.update();return a},remove:function(a){if(u(a,"remove",this))return this;var b=this.recognizers;a=this.get(a);b.splice(v(b,a),1);this.touchAction.update();return this},on:function(a,b){var c=this.handlers;p(A(a),function(a){c[a]=c[a]||[];c[a].push(b)});return this},off:function(a,
b){var c=this.handlers;p(A(a),function(a){b?c[a].splice(v(c[a],b),1):delete c[a]});return this},emit:function(a,b){this.options.domEvents&&Ba(a,b);var c=this.handlers[a]&&this.handlers[a].slice();if(c&&c.length){b.type=a;b.preventDefault=function(){b.srcEvent.preventDefault()};for(var d=0;d<c.length;)c[d](b),d++}},destroy:function(){this.element&&na(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};r(t,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,
STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:Y,Input:l,TouchAction:T,TouchInput:E,MouseInput:F,PointerEventInput:P,TouchMouseInput:Q,SingleTouchInput:la,Recognizer:q,AttrRecognizer:m,Tap:K,Pan:J,Swipe:X,Pinch:U,Rotate:W,Press:V,on:z,off:B,each:p,merge:N,extend:r,inherit:h,bindFn:M,prefixed:D});
"undefined"!=typeof module&&module.exports?module.exports=t:y[qa]=t})(window,document,"Hammer");